--- Makefile.orig	2013-02-08 20:52:24.104334901 +0100
+++ Makefile	2013-02-08 17:19:35.343085315 +0100
@@ -52,4 +52,5 @@
 obj-$(CONFIG_APANIC)		+= apanic.o
 obj-$(CONFIG_SENSORS_AK8975)	+= akm8975.o
 obj-$(CONFIG_SUN4I_VIBRATOR)	+= sun4i-vibrator.o
+obj-$(CONFIG_SUN4I_GPIO_UGLY)	+= sun4i-gpio.o
 obj-$(CONFIG_SUNXI_DBGREG)		+= sunxi-dbgreg.o
